### ISSUE TITLE
keyword style

### ISSUE THREAD

**Issue by clagomess** [clagomess/pirilampo#1]
```css
.keyword{
        font-weight: bold;
        color: #337ab7;
        float: left;
        width: 60px;
        text-align: right;
        margin-right: 4px;
    }
```
